# Site settings
author: Ron Sala
title: The Makefile
header-img: img/home-bg.png
email: ron.sala@gmail.com
copyright_name: Ron Sala
description: > # this means to ignore newlines until "baseurl:"
  Notes from a dev in development
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ronsala

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
